addEventHandler('onClientResourceStart', resourceRoot, function()
    local img = fileOpen('img.jpg')
    local pixels = fileRead(img, fileGetSize(img))
    local pngPixels = dxConvertPixels(pixels, 'png')
    local newImg = fileCreate('img.png')
    fileWrite(newImg, pngPixels)
    fileClose(newImg)
    fileClose(img)
end)
