local circle = createColCircle(0, 0, 1)
local cubboid = createColCuboid(0, 0, 0, 0, 0, 0)
local sphere = createColSphere(0, 0, 0, 0)
local rectangle = createColRectangle(0, 0, 0, 0)
local polygon = createColPolygon(0, 0, 0, 0, 0, 0, 0, 0)
local tube = createColTube(0, 0, 0, 0, 0)

iprint("circle", getColShapeType(circle))
iprint("cubboid", getColShapeType(cubboid))
iprint("sphere", getColShapeType(sphere))
iprint("rectangle", getColShapeType(rectangle))
iprint("polygon", getColShapeType(polygon))
iprint("tube", getColShapeType(tube))