local circle = createColCircle(0, 0, 1)
local cubboid = createColCuboid(0, 0, 0, 0, 0, 0)
local sphere = createColSphere(0, 0, 0, 0)
local rectangle = createColRectangle(0, 0, 0, 0)
local polygon = createColPolygon(0, 0, 0, 0, 0, 0, 0, 0)
local tube = createColTube(0, 0, 0, 0, 0)

iprint("circle", getColShapeType(circle), circle:getShapeType(), circle.shapeType)
iprint("cubboid", getColShapeType(cubboid), cubboid:getShapeType(), cubboid.shapeType)
iprint("sphere", getColShapeType(sphere), sphere:getShapeType(), sphere.shapeType)
iprint("rectangle", getColShapeType(rectangle), rectangle:getShapeType(), rectangle.shapeType)
iprint("polygon", getColShapeType(polygon), polygon:getShapeType(), polygon.shapeType)
iprint("tube", getColShapeType(tube), tube:getShapeType(), tube.shapeType)