// @ts-check
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import path from 'node:path';
import mtasaStarlightThemePlugin from "@multitheftauto/starlight-theme-mtasa";
import { SITE_TITLE, SITE_URL } from "./src/content.constants";
import starlightScrollToTop from 'starlight-scroll-to-top'

export default defineConfig({
  site: SITE_URL,
  build: {
    // Generates /reference/createBlip.html instead of /reference/createBlip/index.html
    // which makes the canonical URL not have a trailing slash.
    format: 'file',
  },
  redirects: {
    '/reference/matrix': '/reference/Matrix',
  },
  i18n: {
    locales: ["en", "es", "fr", "pl"],
    defaultLocale: "en",
    routing: {
      prefixDefaultLocale: false,
    },
  },
  vite: {
    ssr: {
      noExternal: ['zod'],
    },
    resolve: {
      alias: {
        '@src': path.resolve('./src'),
      }
    }
  },
  integrations: [
    starlight({
      plugins: [mtasaStarlightThemePlugin(), starlightScrollToTop({
        tooltipText: {
          "en": "Scroll to top",
          "pl": "Na górę",
        },
        showTooltip: true,
        showProgressRing: false,
      })],
      lastUpdated: true,
      favicon: "favicon.ico",
      title: SITE_TITLE,
      logo: {
        replacesTitle: true,
        light: "./src/assets/images/logo-black.png",
        dark: "./src/assets/images/logo-white.png",
      },
      social: [
        {
          icon: "github",
          label: "GitHub",
          href: "https://github.com/multitheftauto/wiki.multitheftauto.com",
        },
      ],
      editLink: {
        baseUrl:
          "https://github.com/multitheftauto/wiki.multitheftauto.com/edit/main/web/",
      },
      components: {
        // Override some default components
        PageTitle: "./src/overrides/PageTitle.astro",
        Pagination: "./src/overrides/Pagination.astro",
      },
      customCss: ["./src/styles/custom.css"],
      disable404Route: true,
      sidebar: [
        {
          label: "Welcome",
          items: [
            {
              label: "Main page",
              link: "/",
            },
            {
              label: "How you can help",
              link: "/Contributing",
            },
          ],
        },
        {
          label: "Guides",
          items: [
            {label: "Client on Linux manual", link: "/guides/Client-on-Linux-manual"},
            {label: "Steam Deck manual", link: "/guides/SteamDeck"},
            {label: "Scripting introduction", link: "/guides/Scripting-introduction"},
            {label: "Introduction to scripting GUI", link: "/guides/GUI-introduction"},
            {label: "Script security", link: "/guides/Script-security"},
            {label: "Introduction to CEF", link: "/guides/CEF-introduction"},
            {label: "Javascript SDK", link: "/guides/JavaScript-SDK"},
            {label: "PHP SDK", link: "/guides/PHP-SDK"},
          ]
        },
        {
          /* Autogenerate doesn't allow the items to be sorted alphabetically here
            For some reason, the following setting doesn't work at all (https://starlight.astro.build/guides/sidebar/#customizing-autogenerated-links-in-frontmatter):
            sidebar:
              order: X
          */

          label: "Articles",
          items: [
            {label: "Cross-compiling MTASA on Linux using msvc-wine", slug: "articles/wine-build"},
            {label: "Serial", slug: "articles/serial"},
          ]
        },
        {
          label: "Reference",
          items: [
            {
              label: "Resources & Mechanics",
              items: [
                {label: "Element data", link: "/reference/Element_data"},
                {label: "Game processing order", link: "/reference/Game_Processing_Order"},
                {label: "ID Lists", link: "/reference/ID_Lists" },
                {label: "Lua API", link: "/reference/Lua_API" },
                {label: "Meta.xml", link: "/reference/Meta.xml" },
                {label: "Predefined variables", link: '/reference/Predefined_variables'},
                {label: "Resource Web Access", link: "/reference/Resource_Web_Access"},
                {label: "Shaders", link: "/reference/Shaders"},
                {label: "Texture pixels", link: "/reference/Pixels"},
              ],
            },
            {
              label: "API Structure",
              items: [
                {
                  label: "Functions",
                  badge: { text: "Help Wanted", variant: "tip" },
                  items: [
                    {
                      label: "All Functions",
                      link: "/reference/Scripting_Functions",
                    },
                    {
                      label: "Shared Functions",
                      link: "/reference/Shared_Scripting_Functions",
                    },
                    {
                      label: "Client Functions",
                      link: "/reference/Client_Scripting_Functions",
                    },
                    {
                      label: "Server Functions",
                      link: "/reference/Server_Scripting_Functions",
                    },
                  ],
                },
                {
                  label: "Events",
                  items: [
                    { label: "Event System", link: "/reference/Event_System" },
                    {
                      label: "All Events",
                      link: "/reference/Scripting_Events",
                    },
                    {
                      label: "Client Events",
                      link: "/reference/Client_Scripting_Events",
                    },
                    {
                      label: "Server Events",
                      link: "/reference/Server_Scripting_Events",
                    },
                  ],
                },
                {
                  label: "Elements",
                  collapsed: true,
                  items: [
                    { label: "Element Types", link: "/reference/Element" },
                    { label: "Element Tree", link: "/reference/Element_tree" },
                    { label: "Entities", link: "/reference/Entity" },
                    { label: "Visibility", link: "/reference/Visibility" },
                  ],
                },
                {
                  label: "OOP",
                  collapsed: true,
                  items: [
                    { label: "About OOP", link: "/reference/OOP" },
                    { label: "OOP Classes", link: "/reference/OOP_Classes" },
                  ],
                }
              ]
            },
            {
              label: "Configuration",
              items: [
                {
                  label: "MTAServer.conf",
                  link: "/reference/Server_mtaserver.conf",
                },
                { label: "Settings.xml", link: "/reference/Settings_System" },
                { label: "ACL.xml", link: "/reference/Access_Control_List" },
                {
                  label: "Anti cheat guide",
                  link: "/reference/Anti_Cheat_Guide",
                },
              ],
            },
          ],
        },
      ],
    }),
  ],
});
